# sets up a daily schedule to trigger a specific AWS Step Function 
# using EventBridge
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StateMachineArn:
    Type: String
    Description: ARN of the Step Function


Resources:
  # The IAM Role created (EventBridgeInvokeStepFunctionRole) grants EventBridge the necessary 
  # permissions to start the Step Function
  EventBridgeInvokeStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EventBridgeInvokeStepFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowEventBridgeToInvokeStepFunction
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref StateMachineArn

  #defines a rule that triggers the Step Function daily
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: DailyTrigger
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !Ref StateMachineArn # stepFunction.yml
          Id: "StepFunctionTarget"
          RoleArn: !GetAtt EventBridgeInvokeStepFunctionRole.Arn
