# glue job can only return Ref, which returns the resource name. another yaml files, like lambda can return Ref or Arn
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  scriptsBucket:
    Type: String
    Description: S3 bucket name where scripts will be uploaded
  kmsKeyForDEArn:
    Type: String
    Description: KMS Key ARN for encrypting data in GlueJobCsv2Parquet
  kmsKeyForMLArn:
    Type: String
    Description: KMS Key ARN for encrypting data in GlueJobETL


Resources:
  GlueJobRoleForCsv2Parquet:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: GlueJobRoleForCsv2Parquet
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: GlueJobEncryptDecryptPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource: !Ref kmsKeyForDEArn

  GlueJobRoleForETL:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: GlueJobRoleForETL
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: KMSforETL
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - !Ref kmsKeyForDEArn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource:
                  - !Ref kmsKeyForMLArn

  # glue's security configurations
  GlueSecurityConfigurationForCsv2Parquet:
    Type: 'AWS::Glue::SecurityConfiguration'
    Properties:
      Name: GlueSecurityConfigurationForCsv2Parquet
      EncryptionConfiguration:
        S3Encryptions:
          - S3EncryptionMode: SSE-KMS
            KmsKeyArn: !Ref kmsKeyForDEArn

  GlueSecurityConfigurationForETL:
    Type: 'AWS::Glue::SecurityConfiguration'
    Properties:
      Name: GlueSecurityConfigurationForETL
      EncryptionConfiguration:
        S3Encryptions:
          - S3EncryptionMode: SSE-KMS
            KmsKeyArn: !Ref kmsKeyForMLArn

  GlueJobCsv2Parquet:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: GlueJobCsv2Parquet
      Role: !GetAtt GlueJobRoleForCsv2Parquet.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${scriptsBucket}/gluejob/csv2parquet.py
        PythonVersion: '3'
      DefaultArguments:
        '--job-bookmark-option': 'job-bookmark-enable'
      GlueVersion: '4.0'
      MaxCapacity: 2.0
      Timeout: 5
      SecurityConfiguration: !Ref GlueSecurityConfigurationForCsv2Parquet

  GlueJobETL:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: GlueJobETL
      Role: !GetAtt GlueJobRoleForETL.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${scriptsBucket}/gluejob/ETL.py
        PythonVersion: '3'
      DefaultArguments:
        '--job-bookmark-option': 'job-bookmark-enable'
      GlueVersion: '4.0'
      MaxCapacity: 2.0
      Timeout: 12
      SecurityConfiguration: !Ref GlueSecurityConfigurationForETL

Outputs:
  GlueJobCsv2ParquetName:
    Description: csv2parquet name
    Value: !Ref GlueJobCsv2Parquet
  GlueJobETLName:
    Description: ETL name
    Value: !Ref GlueJobETL
